workspace.resolver = "3"
workspace.members = [
    "crate/app/summit",
    "crate/lib/dioxus-ctrl",
    "crate/lib/dioxus-extendable",
    "crate/lib/dioxus-layout",
    "crate/lib/dioxus-window",
    "crate/lib/modwire"
]
workspace.dependencies.dioxus-ctrl.version = "0.1.0"
workspace.dependencies.dioxus-ctrl.path = "crate/lib/dioxus-ctrl"
workspace.dependencies.dioxus-extendable.version = "0.1.0"
workspace.dependencies.dioxus-extendable.path = "crate/lib/dioxus-extendable"
workspace.dependencies.dioxus-layout.version = "0.1.0"
workspace.dependencies.dioxus-layout.path = "crate/lib/dioxus-layout"
workspace.dependencies.dioxus-window.version = "0.1.0"
workspace.dependencies.dioxus-window.path = "crate/lib/dioxus-window"
workspace.dependencies.modwire.version = "0.1.0"
workspace.dependencies.modwire.path = "crate/lib/modwire"
profile.wasm-dev.inherits = "dev"
profile.wasm-dev.opt-level = 1
profile.server-dev.inherits = "dev"
profile.android-dev.inherits = "dev"