workspace.resolver = "3"
workspace.members = [
    "crate/lib/modwire",
    "crate/lib/wasm/js"
]
profile.wasm-dev.inherits = "dev"
profile.wasm-dev.opt-level = 1
profile.server-dev.inherits = "dev"
profile.android-dev.inherits = "dev"