workspace.members = [
    "crate/dx_component/layout",
    "crate/dx_hook/ctrl",
    "crate/dx_hook/window",
    "crate/prim/prelude",
    "crate/prim_util/modesty"
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"