workspace.resolver = "3"
workspace.members = [
    "crate/lib/dx-ctrl",
    "crate/lib/dx-expose",
    "crate/lib/dx-flag",
    "crate/lib/dx-layout",
    "crate/lib/dx-support",
    "crate/lib/dx-window",
    "crate/lib/modwire",
    "crate/lib/core"
]
workspace.exclude = [
    "crate/archive"
]
workspace.dependencies.dioxus-ctrl.version = "0.1.0"
workspace.dependencies.dioxus-ctrl.path = "crate/lib/dioxus-ctrl"
workspace.dependencies.dioxus-extendable.version = "0.1.0"
workspace.dependencies.dioxus-extendable.path = "crate/lib/dioxus-extendable"
workspace.dependencies.dioxus-layout.version = "0.1.0"
workspace.dependencies.dioxus-layout.path = "crate/lib/dioxus-layout"
workspace.dependencies.dioxus-window.version = "0.1.0"
workspace.dependencies.dioxus-window.path = "crate/lib/dioxus-window"
workspace.dependencies.modwire.version = "0.1.0"
workspace.dependencies.modwire.path = "crate/lib/modwire"
profile.wasm-dev.inherits = "dev"
profile.wasm-dev.opt-level = 1
profile.server-dev.inherits = "dev"
profile.android-dev.inherits = "dev"
