workspace.lints.clippy.warnings = "deny"
workspace.lints.clippy.unwrap = "deny"
workspace.resolver = "3"
workspace.members = [
    "crate/dx/summit",
    "crate/dx_component/layout",
    "crate/dx_hook/ctrl",
    "crate/dx_hook/window",
    "crate/kit/prelude",
    "crate/kit/mod_kit",
    "crate/publish/unsudo_dx_hook_ctrl",
    "crate/publish/unsudo_dx_hook_window",
    "crate/publish/unsudo_dx_layout",
    "crate/publish/unsudo_mod_kit"
]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
