workspace.metadata.name = "unsudo"
workspace.resolver = "3"
workspace.members = [
    "crate/lib/dioxus-ctrl",
    "crate/lib/dioxus-extendable",
    "crate/lib/dioxus-layout",
    "crate/lib/dioxus-window",
    "crate/lib/modwire"
]
profile.wasm-dev.inherits = "dev"
profile.wasm-dev.opt-level = 1
profile.server-dev.inherits = "dev"
profile.android-dev.inherits = "dev"