package.name = "window"
package.version = "0.1.0"
package.edition = "2021"
dependencies.prelude.version = "0.1.0"
dependencies.prelude.path = "../../kit/prelude"
dependencies.web-sys.version = ">=0.3.77,<1.0.0"
dependencies.web-sys.features = ["Window", "Event"]
dependencies.dioxus.version = ">=0.6.0,<1.0.0"
dependencies.gloo-timers.version = "*"