package.name = "unsudo_dx_layout"
package.version = "0.1.0"
package.edition = "2021"
package.readme = "./readme.md"
dependencies.layout.version = "0.1.0"
dependencies.layout.path = "../../dx_component/layout"