use super::*;

macro_rules! has {
    ($($field_ident:ident)*) => {
        #[derive(Props)]
        #[derive(Clone)]
        #[derive(PartialEq)]
        #[derive(Default)]
        pub struct AttrsProps {
            $(
                #[props(default=None)] pub $field_ident: MaybeOpcode,
            )*
        }
    };
}

has!(
    access_key
    auto_capitalize
    auto_focus
    class
    content_editable
    data
    dir
    draggable
    enter_key_hint
    export_parts
    hidden
    id
    input_mode
    is
    item_id
    item_prop
    item_ref
    item_scope
    item_type
    lang
    nonce
    part
    popover
    role
    slot
    spell_check
    style
    tab_index
    title
    translate
    align_content
    align_items
    align_self
    alignment_adjust
    alignment_baseline
    all
    alt
    animation
    animation_delay
    animation_direction
    animation_duration
    animation_fill_mode
    animation_name
    animation_play_state
    animation_timing_function
    aspect_ratio
    azimuth
    backdrop_filter
    backface_visibility
    background
    background_attachment
    background_clip
    background_color
    background_image
    background_origin
    background_position
    background_repeat
    background_size
    background_blend_mode
    baseline_shift
    bleed
    bookmark_label
    bookmark_level
    bookmark_state
    border
    border_color
    border_style
    border_width
    border_bottom
    border_bottom_color
    border_bottom_style
    border_bottom_width
    border_left
    border_left_color
    border_left_style
    border_left_width
    border_right
    border_right_color
    border_right_style
    border_right_width
    border_top
    border_top_color
    border_top_style
    border_top_width
    border_collapse
    border_image
    border_image_outset
    border_image_repeat
    border_image_slice
    border_image_source
    border_image_width
    border_radius
    border_bottom_left_radius
    border_bottom_right_radius
    border_top_left_radius
    border_top_right_radius
    border_spacing
    bottom
    box_decoration_break
    box_shadow
    box_sizing
    box_snap
    break_after
    break_before
    break_inside
    buffered_rendering
    caption_side
    clear
    clear_side
    clip
    clip_path
    clip_rule
    color
    color_adjust
    color_correction
    color_interpolation
    color_interpolation_filters
    color_profile
    color_rendering
    column_fill
    column_gap
    column_rule
    column_rule_color
    column_rule_style
    column_rule_width
    column_span
    columns
    column_count
    column_width
    contain
    content
    counter_increment
    counter_reset
    counter_set
    cue
    cue_after
    cue_before
    cursor
    direction
    display
    display_inside
    display_outside
    display_extras
    display_box
    dominant_baseline
    elevation
    empty_cells
    enable_background
    fill
    fill_opacity
    fill_rule
    filter
    float
    float_defer_column
    float_defer_page
    float_offset
    float_wrap
    flow_into
    flow_from
    flex
    flex_basis
    flex_grow
    flex_shrink
    flex_flow
    flex_direction
    flex_wrap
    flood_color
    flood_opacity
    font
    font_family
    font_size
    font_stretch
    font_style
    font_weight
    font_feature_settings
    
);