use ::prelude::*;
use ::dioxus::prelude::*;

bundle!(
    attrs_props
    event_props
);

#[macro_export(local_inner_macros)]
macro_rules! div {
    ($props:ident $($attr:ident $route:ident)*) => {
        ::paste::paste! {
            rsx! {
                div {
                    $(
                        $attr: $props.attrs.$route.to_owned(),
                    )*
                    { $props.children }
                }
            }  
        }
    };
}

#[derive(Props)]
#[derive(Clone)]
#[derive(PartialEq)]
pub struct DivProps {
    pub attrs: AttrsProps,
    pub event: EventProps,
    pub children: Option<Element>
}

#[component]
pub fn Div(props: DivProps) -> Element {
    div!(
        props
        accesskey access_key
        autocapitalize auto_capitalize
        autofocus auto_focus
        class class
        contenteditable content_editable
        data data
        dir dir
        draggable draggable
        enterkeyhint enter_key_hint
        exportparts export_parts
        hidden hidden
        id id
        inputmode input_mode
        is is
        itemid icon
        itemprop item_prop
        itemref item_ref
        itemscope item_scope
        itemtype item_type
        lang lang
        nonce nonce
        part part
        popover popover
        role role
        slot slot
        spellcheck spell_check
        style style
        tabindex tab_index
        title title
        translate translate
        align_content align_content
        align_items align_items
        align_self align_self
        alignment_adjust alignment_adjust
        alignment_baseline alignment_baseline
        all all
        alt alt
        animation animation
        animation_delay animation_delay
        animation_direction animation_direction
        animation_duration animation_duration
        animation_fill_mode animation_fill_mode
        animation_name animation_name
        animation_play_state animation_play_state
        animation_timing_function animation_timing_function
        aspect_ratio aspect_ratio
        azimuth azimuth
        backdrop_filter backdrop_filter
        backface_visibility backface_visibility
        background background
        background_attachment background_attachment
        background_clip background_clip
        background_color background_color
        background_image background_image
        background_origin background_origin
        background_position background_position
        background_repeat background_repeat
        background_size background_size
        background_blend_mode background_blend_mode
        baseline_shift baseline_shift
        bleed bleed
        bookmark_label bookmark_label
        bookmark_level bookmark_level
        bookmark_state bookmark_state
        border border
        border_color border_color
        border_style border_style
        border_width border_width
        border_bottom border_bottom
        border_bottom_color border_bottom_color
        border_bottom_style border_bottom_style
        border_bottom_width border_bottom_width
        border_left border_left
        border_left_color border_left_color
        border_left_style border_left_style
        border_left_width border_left_width
        border_right border_right
        border_right_color border_right_color
        border_right_style border_right_style
        border_right_width border_right_width
        border_top border_top
        border_top_color border_top_color
        border_top_style border_top_style
        border_top_width border_top_width
        border_collapse border_collapse
        border_image border_image
        border_image_outset border_image_outset
        border_image_repeat border_image_repeat
        border_image_slice border_image_slice
        border_image_source border_image_source
        border_image_width border_image_width
        border_radius border_radius
        border_bottom_left_radius border_bottom_left_radius
        border_bottom_right_radius border_bottom_right_radius
        border_top_left_radius border_top_left_radius
        border_top_right_radius border_top_right_radius
        border_spacing border_spacing
        bottom bottom
        box_decoration_break box_decoration_break
        box_shadow box_shadow
        box_sizing box_sizing
        box_snap box_snap
        break_after break_after
        break_before break_before
        break_inside break_inside
        buffered_rendering buffered_rendering
        caption_side caption_side
        clear clear
        clear_side clear_side
        clip clip
        clip_path clip_path
        clip_rule clip_rule
        color color
        color_adjust color_adjust
        color_correction color_correction
        color_interpolation color_interpolation
        color_interpolation_filters color_interpolation_filters
        color_profile color_profile
        color_rendering color_rendering
        column_fill column_fill
        column_gap column_gap
        column_rule column_rule
        column_rule_color column_rule_color
        column_rule_style column_rule_style
        column_rule_width column_rule_width
        column_span column_span
        columns columns
        column_count column_count
        column_width column_width
        contain contain
        content content
        counter_increment counter_increment
        counter_reset counter_reset
        counter_set counter_set
        cue cue
        cue_after cue_after
        cue_before cue_before
        cursor cursor
        direction direction
        display display
        display_inside display_inside
        display_outside display_outside
        display_extras display_extras
        display_box display_box
        dominant_baseline dominant_baseline
        elevation elevation
        empty_cells empty_cells
        enable_background enable_background
        fill fill
        fill_opacity fill_opacity
        fill_rule fill_rule
        filter filter
        float float
        float_defer_column float_defer_column
        float_defer_page float_defer_page
        float_offset float_offset
        float_wrap float_wrap
        flow_into flow_into
        flow_from flow_from
        flex flex
        flex_basis flex_basis
        flex_grow flex_grow
        flex_shrink flex_shrink 
        flex_flow flex_flow
        flex_direction flex_direction
        flex_wrap flex_wrap
        flood_color flood_color
        flood_opacity flood_opacity
        font font
        font_family font_family
        font_size font_size
        font_stretch font_stretch
        font_style font_style
        font_weight font_weight
        font_feature_settings font_feature_settings
        font_kerning font_kerning
        font_language_override font_language_override
        font_size_adjust font_size_adjust
        font_synthesis font_synthesis
        font_variant font_variant
        font_variant_alternates font_variant_alternates
        font_variant_caps font_variant_caps
        font_variant_east_asian font_variant_east_asian
        font_variant_ligatures font_variant_ligatures
        font_variant_numeric font_variant_numeric
        font_variant_position font_variant_position
        footnote_policy footnote_policy
        glyph_orientation_horizontal glyph_orientation_horizontal
        glyph_orientation_vertical glyph_orientation_vertical
        grid grid
        grid_auto_flow grid_auto_flow
        grid_auto_columns grid_auto_columns
        grid_auto_rows grid_auto_rows
        grid_template grid_template
        grid_template_areas grid_template_areas
        grid_template_columns grid_template_columns
        grid_template_rows grid_template_rows
        grid_area grid_area
        grid_column grid_column
        grid_column_start grid_column_start
        grid_column_end grid_column_end
        grid_row grid_row
        grid_row_start grid_row_start
        grid_row_end grid_row_end
        hanging_punctuation hanging_punctuation
        height height
        hyphenate_character hyphenate_character
        hyphenate_limit_chars hyphenate_character
        hyphenate_limit_last hyphenate_limit_last
        hyphenate_limit_lines hyphenate_limit_lines
        hyphenate_limit_zone hyphenate_limit_zone
        hyphens hyphens
        icon icon
        image_orientation image_orientation
        image_resolution image_resolution
        image_rendering image_rendering
        ime ime
        ime_align ime_align
        ime_mode ime_mode
        ime_offset ime_offset
        ime_width ime_width
        initial_letters initial_letters
        inline_box_align inline_box_align
        isolation isolation
        justify_content justify_content
        justify_items justify_items
        justify_self justify_self
        kerning kerning
        left left
        letter_spacing letter_spacing
        lighting_color lighting_color
        line_box_contain line_box_contain
        line_break line_break
        line_grid line_grid
        line_height line_height
        line_slack line_slack
        line_snap line_snap
        list_style list_style
        list_style_image list_style_image
        list_style_position list_style_position
        list_style_type list_style_type
        margin margin 
        margin_bottom margin_bottom
        margin_left margin_left
        margin_right margin_right
        margin_top margin_top
        marker marker
        marker_end marker_end
        marker_mid marker_mid
        marker_pattern marker_pattern
        marker_segment marker_segment
        marker_start marker_start
        marker_knockout_left marker_knockout_left
        marker_knockout_right marker_knockout_right
        marker_side marker_side
        marks marks
        marquee_direction marquee_direction
        marquee_play_count marquee_play_count
        marquee_speed marquee_speed
        marquee_style marquee_style
        mask mask
        mask_image mask_image
        mask_repeat mask_repeat
        mask_position mask_position
        mask_clip mask_clip
        mask_origin mask_origin
        mask_size mask_size
        mask_box mask_box
        mask_box_outset mask_box_outset
        mask_box_repeat mask_box_repeat
        mask_box_slice mask_box_slice
        mask_box_source mask_box_source
        mask_box_width mask_box_width
        mask_type mask_type
        max_height max_height
        max_lines max_lines
        max_width max_width
        min_height min_height
        min_width min_width
        mix_blend_mode mix_blend_mode
        nav_down nav_down
        nav_index nav_index
        nav_left nav_left
        nav_right nav_right
        nav_up nav_up
        object_fit object_fit
        object_position object_position
        offset_after offset_after
        offset_before offset_before
        offset_end offset_end
        offset_start offset_start
        opacity opacity
        order order
        orphans orphans
        outline outline
        outline_color outline_color
        outline_style outline_style
        outline_width outline_width
        outline_offset outline_offset
        overflow overflow
        overflow_x overflow_x
        overflow_y overflow_y
        overflow_style overflow_style
        overflow_wrap overflow_wrap
        padding padding
        padding_bottom padding_bottom
        padding_left padding_left
        padding_right padding_right
        padding_top padding_top
        page page
        page_break_after page_break_after
        page_break_before page_break_before
        page_break_inside page_break_inside
        paint_order paint_order
        pause pause
        pause_after pause_after
        pause_before pause_before
        perspective perspective
        perspective_origin perspective_origin
        pitch pitch
        pitch_range pitch_range
        pitch_during pitch_during
        pointer_events pointer_events
        position position
        quotes quotes
        region_fragment region_fragment
        resize resize
        rest rest
        rest_after rest_after
        rest_before rest_before
        richness richness
        right right
        ruby_align ruby_align
        ruby_merge ruby_merge
        ruby_position ruby_position
        scroll_behavior scroll_behavior
        scroll_snap_coordinate scroll_snap_coordinate
        scroll_snap_destination scroll_snap_destination
        scroll_snap_points_x scroll_snap_points_x
        scroll_snap_points_y scroll_snap_points_y
        scroll_snap_type scroll_snap_type
        shape_image_threshold shape_image_threshold
        shape_inside shape_inside
        shape_margin shape_margin
        shape_outside shape_outside
        shape_rendering shape_rendering
        size size
        speak speak
        speak_as speak_as
        speak_header speak_header
        speak_numeral speak_numeral
        speak_punctuation speak_punctuation
        speech_rate speech_rate
        stop_color stop_color
        stop_opacity stop_opacity
        stress stress
        string_set string_set
        stroke stroke
        stroke_dasharray stroke_dash_array
        stroke_dashoffset stroke_dash_offset
        stroke_linecap stroke_line_cap
        stroke_linejoin stroke_line_join
        stroke_miterlimit stroke_miter_limit
        stroke_opacity stroke_opacity
        stroke_width stroke_width
        tab_size tab_size
        table_layout table_layout
        text_align text_align
        text_align_all text_align_all
        text_align_last text_align_last
        text_anchor text_anchor
        text_combine_upright text_combine_upright
        text_decoration text_decoration
        text_decoration_color text_decoration_color
        text_decoration_line text_decoration_line
        text_decoration_style text_decoration_style
        text_decoration_skip text_decoration_skip
        text_emphasis text_emphasis
        text_emphasis_color text_emphasis_color
        text_emphasis_style text_emphasis_style
        text_emphasis_position text_emphasis_position
        text_emphasis_skip text_emphasis_skip
        text_height text_height
        text_indent text_indent
        text_justify text_justify
        text_orientation text_orientation
        text_overflow text_overflow
        text_rendering text_rendering
        text_shadow text_shadow
        text_size_adjust text_size_adjust
        text_space_collapse text_space_collapse
        text_spacing text_spacing
        text_transform text_transform
        text_underline_position text_underline_position
        text_wrap text_wrap
        top top
        touch_action touch_action
        transform transform
        transform_box transform_box
        transform_origin transform_origin
        transform_style transform_style
        transition transition
        transition_delay transition_delay
        transition_duration transition_duration
        transition_property transition_property
        unicode_bidi unicode_bidi
        vector_effect vector_effect
        vertical_align vertical_align
        visibility visibility
        voice_balance voice_balance
        voice_duration voice_duration
        voice_family voice_family
        voice_pitch voice_pitch
        voice_range voice_range
        voice_stress voice_stress
        voice_volume voice_volume
        volume volume
        white_space white_space
        windows windows
        width width
        will_change will_change
        word_break word_break
        word_spacing word_spacing
        word_wrap word_wrap
        wrap_flow wrap_flow
        wrap_through wrap_through
        writing_mode writing_mode
        gap gap
        list_styler_type list_styler_type
        row_gap row_gap
        transition_timing_function transition_timing_function
        user_select user_select
        webkit_user_select webkit_user_select
        z_index z_index
        aria_current aria_current
        aria_details aria_details
        aria_disabled aria_disabled
        aria_hidden aria_hidden
        aria_invalid aria_invalid
        aria_keyshortcuts aria_key_shortcuts
        aria_label aria_label
        aria_roledescription aria_role_description
        aria_autocomplete aria_auto_complete
        aria_checked aria_checked
        aria_expanded aria_expanded
        aria_haspopup aria_has_popup
        aria_level aria_level
        aria_modal aria_modal
        aria_multiline aria_multi_line
        aria_multiselectable aria_multi_selectable
        aria_orientation aria_orientation
        aria_placeholder aria_placeholder
        aria_pressed aria_pressed
        aria_readonly aria_readonly
        aria_required aria_required
        aria_selected aria_selected
        aria_sort aria_sort
        aria_valuemax aria_value_max
        aria_valuemin aria_value_min
        aria_valuenow aria_value_now
        aria_valuetext aria_value_text
        aria_atomic aria_atomic
        aria_busy aria_busy
        aria_live aria_live
        aria_relevant aria_relevant
        aria_dropeffect aria_drop_effect
        aria_grabbed aria_grabbed
        aria_activedescendant aria_active_descendant
        aria_colcount aria_col_count
        aria_colindex aria_col_index
        aria_colspan aria_col_span
        aria_controls aria_controls
        aria_describedby aria_described_by
        aria_errormessage aria_error_message
        aria_flowto aria_flow_to
        aria_labelledby aria_labelled_by
        aria_owns aria_owns
        aria_posinset aria_pos_in_set
        aria_rowcount aria_row_count
        aria_rowindex aria_row_index
        aria_rowspan aria_row_span
        aria_setsize aria_set_size
    )
}