package.name = "retro_minima"
package.version = "0.1.0"
package.edition = "2021"
dependencies.dioxus.version = ">=0.6.0, < 1.0.0"
dependencies.dioxus.features = ["fullstack"]
features.default = ["web"]
features.web = ["dioxus/web"]
features.desktop = ["dioxus/desktop"]
features.mobile = ["dioxus/mobile"]