package.name = "ctrl"
package.version = "0.1.0"
package.edition = "2021"
dependencies.prelude.version = "0.1.0"
dependencies.prelude.path = "/home/opcode/git_repo/low_bit/crate/prim/prelude"
dependencies.dioxus.version = ">=0.6.0,<1.0.0"