package.name = "ferro_spring"
package.version = "0.1.0"
package.edition = "2021"
dependencies.wasm-bindgen.version = "*"
dependencies.js-sys.version = "*"
dependencies.dioxus.version = "*"
dependencies.serde.version = "*"
dependencies.web-sys.version = "*"
dependencies.gloo-utils.version = "*"
dependencies.gloo-timers.version = "*"