package.name = "summit"
package.version = "0.1.0"
package.edition = "2021"
package.publish = false
dependencies.dioxus-ctrl.workspace = true
dependencies.dioxus-extendable.workspace = true
dependencies.dioxus-layout.workspace = true
dependencies.dioxus-window.workspace = true
dependencies.modwire.workspace = true
dependencies.gloo-timers.version = "*"
dependencies.web-sys.version = "0.3.77"
dependencies.dioxus.version = ">=0.6.0,<1.0.0"
dependencies.dioxus.features = ["fullstack"]
dependencies.dioxus-motion.version = ">=0.3.1,< 1.0.0"
features.default = ["web"]
features.web = ["dioxus/web"]
features.desktop = ["dioxus/desktop"]
features.mobile = ["dioxus/mobile"]