package.name = "retro_minima"
package.version = "0.1.0"
package.edition = "2021"
dependencies.prelude.version = "0.1.0"
dependencies.prelude.path = "../../kit/prelude"
dependencies.layout.version = "0.1.0"
dependencies.layout.path = "../../dx_component/layout"
dependencies.ctrl.version = "0.1.0"
dependencies.ctrl.path = "../../dx_hook/ctrl"
dependencies.window.version = "0.1.0"
dependencies.window.path = "../../dx_hook/window"
dependencies.gloo-timers.version = "*"
dependencies.web-sys.version = "0.3.77"
dependencies.dioxus.version = ">=0.6.0,<1.0.0"
dependencies.dioxus.features = ["fullstack"]
dependencies.dioxus-motion.version = ">=0.3.1,< 1.0.0"
features.default = ["web"]
features.web = ["dioxus/web"]
features.desktop = ["dioxus/desktop"]
features.mobile = ["dioxus/mobile"]