package.name = "extendable"
package.version = "0.1.0"
package.edition = "2021"
package.description = "A lightweight Dioxus utility library for extending low-level HTML attributes, and events in higher-level components. Rust lacks a native rest/spread operator (ie. `...props` in JavaScript/React). This crate fills that gap with ergonomic helpers for attribute, and event drilling."
package.license = "Apache-2.0"
package.keywords = [
    "dioxus",
    "props",
    "component",
    "lib",
]
package.categories = [
    "web",
    "gui",
    "wasm",
    "development-tools",
]
package.readme = "readme.md"
package.homepage = "https://github.com/snqre/unsudo"
package.repository = "https://github.com/snqre/unsudo/tree/master/crate/dx_lib/extendable"
package.exclude = [
    "/target",
]
dependencies.dioxus.version = ">=0.6.3,<1.0.0"
dependencies.prelude.version = "0.1.0"
dependencies.prelude.path = "../../util/prelude"
dependencies.paste.version = ">=1.0.15,<2.0.0"