use super::*;

pub type Rad0<T> = Q<0, T, RadianMode>;
pub type Rad1<T> = Q<1, T, RadianMode>;
pub type Rad2<T> = Q<2, T, RadianMode>;
pub type Rad3<T> = Q<3, T, RadianMode>;
pub type Rad4<T> = Q<4, T, RadianMode>;
pub type Rad5<T> = Q<5, T, RadianMode>;
pub type Rad6<T> = Q<6, T, RadianMode>;
pub type Rad7<T> = Q<7, T, RadianMode>;
pub type Rad8<T> = Q<8, T, RadianMode>;
pub type Rad9<T> = Q<9, T, RadianMode>;
pub type Rad10<T> = Q<10, T, RadianMode>;
pub type Rad11<T> = Q<11, T, RadianMode>;
pub type Rad12<T> = Q<12, T, RadianMode>;
pub type Rad13<T> = Q<13, T, RadianMode>;
pub type Rad14<T> = Q<14, T, RadianMode>;
pub type Rad15<T> = Q<15, T, RadianMode>;
pub type Rad16<T> = Q<16, T, RadianMode>;
pub type Rad17<T> = Q<17, T, RadianMode>;
