package.name = "unsudo_dioxus"
package.version = "0.1.0"
dependencies.extender.version = "*"
dependencies.extender.path = "../../dx_lib/extendable"
dependencies.layout.version = "*"
dependencies.layout.path = "../../dx_lib/layout"
dependencies.window.version = "*"
dependencies.window.path = "../../dx_lib/window"